image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t alprcamera-module .
    - docker run alprcamera-module npm install
    - docker run alprcamera-module npm run build  
  artifacts:
    paths:
      - lib/  
      
deploy:
  stage: deploy
  script:
    - docker run -e CI_SERVER_HOST -e CI_PROJECT_ID -e CI_JOB_TOKEN alprcamera-module sh -c "echo \"@alprapp:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/\" > .npmrc && echo \"//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}\" >> .npmrc && npm publish"
  only:
    - main
  dependencies:
    - build  

